### ISSUE TITLE
Prompt Clarifications

### ISSUE THREAD

**Issue by zwhile** [nealshuh/defectiveballcics191#7]
Can you clarify _"one chance to use the electronic weighing machine"_?  Does this mean that I can only see one weight, i.e. I can't weigh a box of balls, remove a ball, and then see the updated weight?  So I could only get the box's initial weight?

I won't look at your solution README until I submit mine, so it may be the case that this is addressed in the solution haha.

**Comment by nealshuh** [comment]
Yes, using that method you'd only be able to get the initial weight of the box using that method. Basically one chance means that you will only be able to use the weight of one group of objects you put on the weigh scale. For example, say that you weigh the combined weight of 1 ball from each box by putting them all on the machine once. That is the only information you could get from the electronic weighing machine for the rest of the puzzle.

**Comment by nealshuh** [comment]
I updated the prompt so that was more clear.

**Comment by zwhile** [comment]
Thanks!
